import type { ClinicConfig } from "@/config/types";

export const clinic = {
  name: "Alento Fisioterapia",
  siteUrl: "https://alento.example",
  tagline: "Fisioterapia e quiropraxia em São José do Rio Preto",
  description: "Cuidado em fisioterapia e quiropraxia com avaliação individualizada, escuta atenta e acompanhamento próximo em São José do Rio Preto.",
  city: "São José do Rio Preto",
  state: "SP",
  whatsapp: "5517900000000",
  phone: "(17) 90000-0000",
  phoneInternational: "+5517900000000",
  email: "contato@alento.example",
  address: "Rua das Acácias, 000 — Jardim Vivendas, São José do Rio Preto — SP",
  addressDetails: { streetAddress: "Rua das Acácias, 000 — Jardim Vivendas", addressLocality: "São José do Rio Preto", addressRegion: "SP", addressCountry: "BR" },
  hours: { weekdays: "Seg–sex, 7h–20h", saturday: "Sáb, 8h–12h" },
  openingHours: [
    { days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], opens: "07:00", closes: "20:00" },
    { days: ["Saturday"], opens: "08:00", closes: "12:00" },
  ],
  mapsEmbedUrl: "https://www.google.com/maps/embed?pb=placeholder",
  professional: {
    name: "Dra. Marina Azevedo",
    registration: "Crefito-3 000000-F",
    bio: [
      "Fisioterapeuta com atuação em cuidado musculoesquelético, reabilitação esportiva e quiropraxia. Seu trabalho começa pela escuta e por uma avaliação cuidadosa do movimento.",
      "Conduz cada acompanhamento com explicações claras, decisões compartilhadas e respeito ao ritmo de cada pessoa, integrando terapia manual, exercício e orientação.",
    ],
    image: "/img/sobre/physiotherapy-consultation.jpg",
    imageAlt: "Fisioterapeuta conversando com paciente durante uma consulta",
    secondaryImage: "/img/clinica/therapy-room.jpg",
    secondaryImageAlt: "Sala acolhedora preparada para atendimento de fisioterapia",
    specialties: [
      "Graduação em Fisioterapia — formação demonstrativa",
      "Especialização em Fisioterapia Musculoesquelética — placeholder",
      "Formação em Quiropraxia Clínica — placeholder",
      "Atualização em Reabilitação Esportiva — placeholder",
    ],
  },
  // PLACEHOLDER DE DEMO — em cliente real, usar apenas números verificáveis (regras de publicidade do Crefito)
  stats: [
    { value: "12+", label: "anos de experiência" },
    { value: "3.500+", label: "pacientes atendidos" },
    { value: "480+", label: "atletas acompanhados" },
    { value: "4,9", label: "avaliação média" },
  ],
  treatments: [
    {
      slug: "reabilitacao-do-joelho",
      title: "Reabilitação do joelho",
      category: "Fisioterapia ortopédica",
      summary: "Avaliação e acompanhamento para recuperar mobilidade, força e segurança nas atividades diárias.",
      description: [
        "O cuidado começa com uma avaliação do movimento, da força e das atividades que mais importam para você. A partir dela, construímos um plano progressivo e compatível com a sua rotina.",
        "O acompanhamento pode incluir exercícios terapêuticos, educação sobre carga e recursos manuais, sempre revistos conforme sua resposta e as orientações da equipe médica quando houver.",
      ],
      conditions: ["Dor anterior no joelho", "Lesões ligamentares", "Alterações de menisco", "Retorno após imobilização"],
      howItWorks: ["Avaliação funcional individual", "Plano progressivo de exercícios", "Reavaliações ao longo do acompanhamento"],
      averageSessions: "Definido após a avaliação e ajustado conforme a evolução clínica.",
      faq: [
        { question: "Posso fazer fisioterapia mesmo com dor?", answer: "Sim, após avaliação. A intensidade e os exercícios são adaptados aos sinais apresentados em cada sessão." },
        { question: "Preciso levar exames?", answer: "Se você já possui exames ou relatórios, leve-os. Eles complementam a avaliação, mas não substituem o exame funcional." },
      ],
      image: "/img/tratamentos/knee-rehabilitation.jpg",
      imageAlt: "Pessoa realizando exercício orientado para reabilitação do joelho",
    },
    {
      slug: "coluna-e-quiropraxia",
      title: "Coluna e quiropraxia",
      category: "Cuidado da coluna",
      summary: "Abordagem individual para desconfortos na coluna, com terapia manual, movimento e orientação.",
      description: [
        "A avaliação considera seus sintomas, hábitos, histórico e a forma como o corpo responde aos movimentos. O objetivo é compreender fatores que podem estar relacionados ao desconforto.",
        "Quando indicada, a quiropraxia integra o plano com técnicas manuais e exercícios. A conduta é explicada previamente e respeita suas preferências e condições clínicas.",
      ],
      conditions: ["Dor lombar", "Desconforto cervical", "Rigidez torácica", "Limitação de movimento"],
      howItWorks: ["Triagem de segurança", "Técnicas manuais quando indicadas", "Exercícios e orientações para a rotina"],
      averageSessions: "A frequência depende da avaliação, dos objetivos e da resposta ao acompanhamento.",
      faq: [
        { question: "A quiropraxia é indicada para todo mundo?", answer: "Não. Antes de qualquer técnica, realizamos uma triagem e conversamos sobre alternativas adequadas para cada pessoa." },
        { question: "O atendimento inclui exercícios?", answer: "Sempre que indicados, os exercícios ajudam a ampliar autonomia e são ensinados de forma gradual." },
      ],
      image: "/img/tratamentos/back-pain-treatment.jpg",
      imageAlt: "Atendimento fisioterapêutico para mobilidade e cuidado da coluna",
    },
    {
      slug: "reabilitacao-do-ombro",
      title: "Reabilitação do ombro",
      category: "Fisioterapia ortopédica",
      summary: "Cuidado progressivo para movimentos do ombro no trabalho, no esporte e na vida cotidiana.",
      description: [
        "Investigamos mobilidade, força, controle e as tarefas que provocam desconforto. Essa leitura orienta um plano com metas claras e progressão cuidadosa.",
        "As sessões podem combinar exercícios específicos, terapia manual e ajustes de carga para apoiar a retomada gradual das atividades importantes para você.",
      ],
      conditions: ["Tendinopatias", "Dor ao elevar o braço", "Instabilidade", "Pós-operatório do ombro"],
      howItWorks: ["Avaliação de mobilidade e força", "Exercícios orientados", "Progressão para tarefas específicas"],
      averageSessions: "O plano é individual e a previsão é discutida após a primeira avaliação.",
      faq: [
        { question: "Devo parar de usar o braço?", answer: "Nem sempre. A avaliação ajuda a definir quais movimentos podem ser mantidos e quais cargas precisam ser ajustadas temporariamente." },
        { question: "Atendem casos pós-operatórios?", answer: "Sim, com respeito às orientações médicas e aos critérios de progressão de cada procedimento." },
      ],
      image: "/img/tratamentos/shoulder-therapy.jpg",
      imageAlt: "Fisioterapeuta acompanhando exercício terapêutico para o ombro",
    },
    {
      slug: "liberacao-miofascial",
      title: "Liberação miofascial",
      category: "Terapia manual",
      summary: "Técnicas manuais integradas a um plano ativo para conforto e mobilidade.",
      description: [
        "A liberação miofascial pode ser utilizada como parte do atendimento quando a avaliação identifica benefício para mobilidade ou percepção de tensão.",
        "Ela não é aplicada de forma isolada: exercícios e orientações ajudam a relacionar o efeito da técnica às necessidades reais de movimento e atividade.",
      ],
      conditions: ["Sensação de tensão muscular", "Rigidez de movimento", "Sobrecarga esportiva", "Desconforto associado à rotina"],
      howItWorks: ["Avaliação da queixa", "Aplicação confortável da técnica", "Integração com exercícios ativos"],
      averageSessions: "A indicação e a frequência são definidas individualmente.",
      faq: [
        { question: "A técnica precisa doer?", answer: "Não. A pressão é ajustada ao seu conforto e à resposta dos tecidos durante o atendimento." },
        { question: "Pode ser feita antes de competições?", answer: "A decisão depende do momento de preparação, da modalidade e da resposta individual do atleta." },
      ],
      image: "/img/tratamentos/myofascial-release.jpg",
      imageAlt: "Aplicação de técnica manual de liberação miofascial",
    },
    {
      slug: "fisioterapia-esportiva",
      title: "Fisioterapia esportiva",
      category: "Esporte e performance",
      summary: "Reabilitação e retorno gradual ao esporte orientados pelas demandas da sua modalidade.",
      description: [
        "O plano considera a lesão, o estágio de recuperação, a modalidade e o nível de prática. Testes funcionais ajudam a acompanhar capacidades importantes para o retorno.",
        "Trabalhamos em diálogo com treinadores e profissionais de saúde quando necessário, ajustando cargas e critérios sem estabelecer prazos ou resultados universais.",
      ],
      conditions: ["Lesões musculares", "Entorses", "Tendinopatias", "Retorno ao esporte"],
      howItWorks: ["Mapeamento das demandas esportivas", "Treino progressivo de força e controle", "Testes funcionais de acompanhamento"],
      averageSessions: "Varia conforme a lesão, a modalidade e os critérios funcionais observados.",
      faq: [
        { question: "Quando posso voltar a treinar?", answer: "A decisão considera sintomas, capacidade física e demandas do esporte, em conjunto com as orientações médicas quando aplicável." },
        { question: "Vocês atendem atletas amadores?", answer: "Sim. O acompanhamento é adaptado tanto à prática recreativa quanto à competitiva." },
      ],
      image: "/img/atletas/sports-physiotherapy.jpg",
      imageAlt: "Atleta durante atendimento de fisioterapia esportiva",
    },
    {
      slug: "reabilitacao-pos-cirurgica",
      title: "Reabilitação pós-cirúrgica",
      category: "Recuperação funcional",
      summary: "Acompanhamento por fases, alinhado às orientações médicas e às necessidades da sua rotina.",
      description: [
        "Após uma cirurgia, cada fase tem objetivos e cuidados específicos. Organizamos o atendimento a partir do procedimento realizado, das orientações da equipe médica e da avaliação funcional.",
        "Mobilidade, força e tarefas do cotidiano são trabalhadas gradualmente. Reavaliações ajudam a adaptar o plano e tornar os próximos passos mais claros.",
      ],
      conditions: ["Cirurgias de joelho", "Cirurgias de ombro", "Cirurgias de quadril", "Outros procedimentos ortopédicos"],
      howItWorks: ["Revisão das orientações médicas", "Metas por fase de recuperação", "Progressão funcional acompanhada"],
      averageSessions: "Depende do procedimento, da fase pós-operatória e das orientações da equipe responsável.",
      faq: [
        { question: "Quando devo iniciar?", answer: "O momento é definido pelo cirurgião e pelas características do procedimento. Entre em contato para alinharmos as orientações recebidas." },
        { question: "Vocês conversam com meu médico?", answer: "Quando necessário e com sua autorização, podemos alinhar informações relevantes com os profissionais envolvidos." },
      ],
      image: "/img/tratamentos/post-surgery-rehabilitation.jpg",
      imageAlt: "Paciente em exercício acompanhado de reabilitação pós-cirúrgica",
    },
  ],
  audiences: [
    { slug: "atletas", title: "Atletas", text: "Acompanhamento conectado às demandas do treino e ao retorno gradual à modalidade.", image: "/img/atletas/stretching-athlete.jpg", imageAlt: "Atleta realizando alongamento durante preparação física" },
    { slug: "pos-cirurgico", title: "Pós-cirúrgico", text: "Cuidado organizado por fases e alinhado às orientações do procedimento realizado.", image: "/img/atletas/athlete-recovery.jpg", imageAlt: "Pessoa em acompanhamento durante recuperação funcional" },
    { slug: "dor-cronica", title: "Dor crônica", text: "Escuta, educação e movimento para construir estratégias possíveis no dia a dia.", image: "/img/sobre/posture-assessment.jpg", imageAlt: "Fisioterapeuta realizando avaliação de postura e movimento" },
    { slug: "idosos", title: "Idosos", text: "Exercícios adaptados para mobilidade, força, equilíbrio e autonomia funcional.", image: "/img/tratamentos/elderly-physiotherapy.jpg", imageAlt: "Pessoa idosa realizando exercício com acompanhamento fisioterapêutico" },
  ],
  faq: [
    { question: "A clínica atende convênio?", answer: "Os atendimentos são particulares. Fornecemos os documentos necessários para que você consulte a possibilidade de reembolso diretamente com seu convênio." },
    { question: "Preciso de pedido médico?", answer: "Não é obrigatório para a primeira avaliação fisioterapêutica. Se você tiver encaminhamento, relatório ou exames, eles podem complementar o atendimento." },
    { question: "Quanto dura uma sessão?", answer: "Em geral, reserve cerca de 50 minutos. O tempo pode variar conforme as necessidades identificadas no atendimento." },
    { question: "Quantas sessões vou precisar?", answer: "Não existe um número igual para todos. Após a avaliação, conversamos sobre uma estimativa e reavaliamos o plano ao longo do processo." },
    { question: "O que devo levar?", answer: "Leve documento, exames ou relatórios que já possua e use uma roupa confortável que permita avaliar a região relacionada à queixa." },
    { question: "Como funciona a primeira avaliação?", answer: "Conversamos sobre seu histórico e objetivos, realizamos testes físicos pertinentes e explicamos as possibilidades de acompanhamento antes de iniciar qualquer conduta." },
  ],
  social: { instagram: "#" },
  navigation: {
    treatments: "Tratamentos", about: "Sobre", blog: "Blog", contact: "Contato", schedule: "Agendar avaliação",
    openMenu: "Abrir menu", closeMenu: "Fechar menu", treatmentsMenu: "Abrir lista de tratamentos",
    mainMenu: "Menu principal",
  },
  footer: {
    treatmentsTitle: "Tratamentos", contactTitle: "Contato", linksTitle: "Navegue", privacy: "Política de privacidade",
    creditsPrefix: "Site por", creditsName: "CiudadLab",
  },
  whatsappUi: {
    floatingLabel: "Agendar avaliação pelo WhatsApp",
    defaultMessage: "Olá! Vim pelo site e gostaria de agendar uma avaliação.",
    treatmentMessagePrefix: "Olá! Vim pelo site e gostaria de agendar uma avaliação para",
  },
  seo: {
    homeTitle: "Alento Fisioterapia | Fisioterapia e quiropraxia em São José do Rio Preto",
    homeDescription: "Fisioterapia e quiropraxia com avaliação individualizada e acompanhamento próximo em São José do Rio Preto.",
    styleguideTitle: "Styleguide",
    styleguideDescription: "Fundação visual do template Alento Fisioterapia.",
  },
  analytics: {
    consentText: "Usamos cookies de análise somente com sua autorização para entender o uso do site.",
    accept: "Aceitar",
    decline: "Recusar",
    privacyLink: "Política de privacidade",
  },
  home: {
    hero: {
      locationLabel: "São José do Rio Preto · SP",
      title: "Recupere o movimento com cuidado e acompanhamento próximo.",
      description: "Fisioterapia e quiropraxia em São José do Rio Preto, com um plano de cuidado que respeita sua história, sua rotina e seus objetivos.",
      primaryCta: "Agendar avaliação",
      secondaryCta: "Conhecer tratamentos",
      trustText: "Atendimento profissional registrado",
      video: "/videos/video-hero-web.mp4",
      poster: "/img/hero/hero-poster.jpg",
      mediaAlt: "Fisioterapeuta acompanhando paciente durante atendimento na clínica",
    },
    treatments: {
      eyebrow: "Tratamentos",
      title: "Cuidado direcionado ao que você precisa mover.",
      description: "Cada acompanhamento começa com uma avaliação individual e evolui com critérios claros, respeitando seu momento e seus objetivos.",
      allLink: "Ver todos os tratamentos",
    },
    audiences: {
      eyebrow: "Para quem é",
      title: "Cuidado para diferentes momentos da vida.",
      description: "Do retorno ao esporte à busca por mais autonomia, o plano terapêutico parte das necessidades de cada pessoa.",
    },
    process: {
      eyebrow: "Como funciona",
      title: "Como funciona o seu acompanhamento",
      description: "Um caminho claro, construído em conjunto e revisto de acordo com as suas necessidades ao longo do processo.",
      cta: "Agendar minha avaliação",
      steps: [
        { number: "01", title: "Primeiro contato pelo WhatsApp", text: "Você conta brevemente o que precisa e nossa equipe ajuda a encontrar o melhor horário para a avaliação." },
        { number: "02", title: "Avaliação individual", text: "Conversamos sobre seu histórico, seus objetivos e avaliamos os movimentos relacionados à sua rotina." },
        { number: "03", title: "Plano de cuidado", text: "Explicamos as possibilidades e organizamos um plano individual, com prioridades e próximos passos claros." },
        { number: "04", title: "Acompanhamento e reavaliações", text: "A evolução é acompanhada de perto, com ajustes de carga e estratégia sempre que necessário." },
      ],
    },
    professional: {
      eyebrow: "Quem cuida de você",
      aboutLink: "Conheça a clínica",
      specialtiesTitle: "Formações e áreas de atuação",
    },
    testimonials: {
      eyebrow: "Experiências de cuidado",
      title: "Histórias que começam com escuta e confiança.",
      description: "Relatos ilustrativos de como um acompanhamento próximo pode ser percebido em diferentes momentos da recuperação.",
      exampleNote: "Depoimentos ilustrativos do modelo de demonstração.",
      items: [
        { text: "Desde a primeira avaliação, entendi melhor o que estava acontecendo e me senti segura para avançar etapa por etapa.", name: "Marina S.", context: "Reabilitação do joelho", isExample: true },
        { text: "O plano se adaptou à minha rotina e cada exercício tinha uma explicação clara. O acompanhamento fez toda a diferença para a minha confiança.", name: "Carlos R.", context: "Cuidado da coluna", isExample: true },
        { text: "Gostei de participar das decisões e acompanhar minha evolução com critérios objetivos, sem pressa e sem promessas irreais.", name: "Ana P.", context: "Fisioterapia esportiva", isExample: true },
      ],
    },
    faq: {
      eyebrow: "Dúvidas comuns",
      title: "Perguntas frequentes",
      description: "Informações para você chegar à primeira avaliação com mais tranquilidade.",
      cta: "Ainda com dúvidas? Fale com a gente",
    },
    contact: {
      eyebrow: "Contato",
      title: "Estamos em São José do Rio Preto.",
      description: "Entre em contato para conversar com a equipe ou organizar sua primeira avaliação.",
      addressLabel: "Endereço",
      phoneLabel: "Telefone",
      emailLabel: "E-mail",
      hoursLabel: "Horários",
      directionsCta: "Como chegar",
      mapTitle: "Localização da Alento Fisioterapia no mapa",
    },
    finalCta: {
      eyebrow: "Comece com uma conversa",
      title: "Seu movimento merece um cuidado feito para você.",
      description: "Conte para a nossa equipe o que você precisa e agende uma avaliação individual.",
      button: "Agendar avaliação",
    },
  },
  pages: {
    treatments: {
      eyebrow: "Especialidades",
      title: "Tratamentos pensados para o seu movimento.",
      description: "Conheça as áreas de atendimento e encontre um cuidado alinhado às necessidades da sua rotina.",
      metadataTitle: "Tratamentos de fisioterapia em São José do Rio Preto",
      metadataDescription: "Tratamentos de fisioterapia, quiropraxia e reabilitação individualizada em São José do Rio Preto.",
    },
    treatmentDetail: {
      conditionsTitle: "Para quais condições",
      howTitle: "Como funciona",
      durationTitle: "Duração do acompanhamento",
      summaryTitle: "Seu acompanhamento",
      professionalLabel: "Responsável pelo atendimento",
      schedulePrefix: "Agendar avaliação para",
      otherEyebrow: "Continue conhecendo",
      otherTitle: "Outros tratamentos",
      medicalTherapyType: "Fisioterapia",
    },
    about: {
      metadataTitle: "Sobre a clínica em São José do Rio Preto",
      eyebrow: "Sobre a Alento",
      title: "Cuidado próximo, decisões claras e movimento com propósito.",
      description: "Conheça a profissional e os princípios que orientam cada atendimento na Alento Fisioterapia.",
      metadataDescription: "Conheça a Alento Fisioterapia, sua profissional responsável e a forma de cuidar em São José do Rio Preto.",
      headerImage: "/img/clinica/clinic-interior-minimal-2.jpg",
      headerImageAlt: "Ambiente interno claro e acolhedor da clínica de fisioterapia",
      valuesEyebrow: "Nossa forma de cuidar",
      valuesTitle: "Princípios presentes em cada encontro.",
      valuesDescription: "Uma experiência de cuidado construída com atenção, informação e continuidade.",
      values: [
        { title: "Escuta", text: "A história, as necessidades e os objetivos de cada pessoa orientam o início do acompanhamento.", icon: "ear" },
        { title: "Clareza", text: "Avaliação, possibilidades e próximos passos são explicados de forma simples e transparente.", icon: "message" },
        { title: "Acompanhamento", text: "O plano é revisto ao longo do processo para acompanhar respostas e novas necessidades.", icon: "path" },
      ],
      galleryEyebrow: "A clínica",
      galleryTitle: "Um espaço preparado para receber você.",
      gallery: [
        { src: "/img/clinica/clinic-interior-minimal-2.jpg", alt: "Recepção minimalista e iluminada da clínica" },
        { src: "/img/clinica/therapy-room.jpg", alt: "Sala privativa de atendimento fisioterapêutico" },
        { src: "/img/clinica/gym-rehabilitation-equipment.jpg", alt: "Área de exercícios com equipamentos para reabilitação" },
        { src: "/img/clinica/massage-table-2.jpg", alt: "Maca preparada em ambiente de atendimento" },
        { src: "/img/clinica/physiotherapy-clinic.jpg", alt: "Espaço funcional para exercícios e acompanhamento" },
      ],
    },
    contact: {
      eyebrow: "Fale com a equipe",
      title: "Contato e localização",
      description: "Encontre os canais da clínica e escolha a forma mais simples de iniciar uma conversa.",
      metadataTitle: "Contato em São José do Rio Preto",
      metadataDescription: "Contato, endereço e horários da Alento Fisioterapia em São José do Rio Preto.",
    },
    privacy: {
      metadataTitle: "Política de privacidade",
      eyebrow: "Privacidade",
      title: "Política de privacidade",
      description: "Informações gerais sobre o tratamento de dados neste site demonstrativo.",
      metadataDescription: "Modelo de política de privacidade e tratamento de dados da Alento Fisioterapia.",
      notice: "Modelo demonstrativo — este conteúdo deve ser revisado e aprovado pelo cliente e por sua assessoria jurídica antes da publicação.",
      sections: [
        { title: "Dados coletados", paragraphs: ["Este site não possui formulário próprio e não coleta diretamente dados pessoais de saúde. Ao escolher conversar pelo WhatsApp, você passa a utilizar uma plataforma externa e seus dados são tratados conforme as políticas desse serviço.", "Se o Google Analytics 4 estiver configurado, cookies e informações técnicas de navegação poderão ser utilizados para medir visitas, páginas acessadas e duração da sessão. O armazenamento de dados analíticos permanece desativado até que você escolha aceitar no banner de consentimento."] },
        { title: "Finalidade do tratamento", paragraphs: ["Os dados eventualmente recebidos pelos canais de contato são utilizados para responder solicitações, organizar atendimentos e fornecer informações sobre os serviços da clínica. Dados de navegação, quando coletados, servem para compreender o uso do site e melhorar sua experiência."] },
        { title: "Compartilhamento e conservação", paragraphs: ["As informações não devem ser comercializadas. Elas podem ser processadas por fornecedores necessários à comunicação, hospedagem ou análise do site, sempre de acordo com contratos e medidas de segurança adequadas.", "Os dados devem ser mantidos somente pelo período necessário ao atendimento das finalidades informadas ou ao cumprimento de obrigações legais e regulatórias."] },
        { title: "Direitos do titular", paragraphs: ["Nos termos da Lei Geral de Proteção de Dados, você pode solicitar confirmação de tratamento, acesso, correção, anonimização, portabilidade ou eliminação de dados, observadas as hipóteses legais de conservação."] },
        { title: "Contato sobre privacidade", paragraphs: ["Para dúvidas ou solicitações relacionadas aos seus dados pessoais, entre em contato pelo e-mail informado nesta página. A identidade do solicitante poderá ser confirmada antes do atendimento do pedido."] },
      ],
    },
    notFound: {
      title: "Página não encontrada",
      description: "O endereço que você tentou acessar não existe ou foi alterado.",
      homeButton: "Voltar ao início",
      treatmentsButton: "Ver tratamentos",
    },
    breadcrumbs: { home: "Início", treatments: "Tratamentos", about: "Sobre", contact: "Contato", privacy: "Política de privacidade" },
  },
} satisfies ClinicConfig;
